// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB01Kjb-4_i3WjDFjj6fPVPxZoDvbQvYi4',
    appId: '1:125219760150:web:df89ebf52f385badc92d37',
    messagingSenderId: '125219760150',
    projectId: 'chat-flutter-de59f',
    authDomain: 'chat-flutter-de59f.firebaseapp.com',
    storageBucket: 'chat-flutter-de59f.appspot.com',
    measurementId: 'G-F5HE2ES8KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0J2iEOEXpotag87xv8knXsWggd8_Q-ck',
    appId: '1:125219760150:android:63000451983c9c6ac92d37',
    messagingSenderId: '125219760150',
    projectId: 'chat-flutter-de59f',
    storageBucket: 'chat-flutter-de59f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLLCuyBUdMxRNZTZwfVkj835-UDxY-gS8',
    appId: '1:125219760150:ios:ded42f2043cbb915c92d37',
    messagingSenderId: '125219760150',
    projectId: 'chat-flutter-de59f',
    storageBucket: 'chat-flutter-de59f.appspot.com',
    iosBundleId: 'com.example.chatflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLLCuyBUdMxRNZTZwfVkj835-UDxY-gS8',
    appId: '1:125219760150:ios:ded42f2043cbb915c92d37',
    messagingSenderId: '125219760150',
    projectId: 'chat-flutter-de59f',
    storageBucket: 'chat-flutter-de59f.appspot.com',
    iosBundleId: 'com.example.chatflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB01Kjb-4_i3WjDFjj6fPVPxZoDvbQvYi4',
    appId: '1:125219760150:web:581b5ca32fbe048ec92d37',
    messagingSenderId: '125219760150',
    projectId: 'chat-flutter-de59f',
    authDomain: 'chat-flutter-de59f.firebaseapp.com',
    storageBucket: 'chat-flutter-de59f.appspot.com',
    measurementId: 'G-NHZSMSCQWP',
  );
}

